
package org.ragna.kalin.ch02.ts.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeServer", targetNamespace = "http://ts.ch02.kalin.ragna.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeAsString", targetNamespace = "http://ts.ch02.kalin.ragna.org/", className = "org.ragna.kalin.ch02.ts.client.GetTimeAsString")
    @ResponseWrapper(localName = "getTimeAsStringResponse", targetNamespace = "http://ts.ch02.kalin.ragna.org/", className = "org.ragna.kalin.ch02.ts.client.GetTimeAsStringResponse")
    @Action(input = "http://ts.ch02.kalin.ragna.org/TimeServer/getTimeAsStringRequest", output = "http://ts.ch02.kalin.ragna.org/TimeServer/getTimeAsStringResponse")
    public String getTimeAsString();

    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeAsElapsed", targetNamespace = "http://ts.ch02.kalin.ragna.org/", className = "org.ragna.kalin.ch02.ts.client.GetTimeAsElapsed")
    @ResponseWrapper(localName = "getTimeAsElapsedResponse", targetNamespace = "http://ts.ch02.kalin.ragna.org/", className = "org.ragna.kalin.ch02.ts.client.GetTimeAsElapsedResponse")
    @Action(input = "http://ts.ch02.kalin.ragna.org/TimeServer/getTimeAsElapsedRequest", output = "http://ts.ch02.kalin.ragna.org/TimeServer/getTimeAsElapsedResponse")
    public long getTimeAsElapsed();

}
